### ISSUE TITLE
Unable to run jar on Amazon JVM

### ISSUE THREAD

**Issue by spark85** [jenkinsci/lib-file-leak-detector#155]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Mac Os Ventura 13.5.2, Java JVM Amazon Corretto 17 & 20. (Tried with multiple sub-releases)

### Reproduction steps

1) Setup the Amazon Corretto JVM as java home and set it on your zsh path. 
2) setup an Android gradle build (this is optional as it is unrelated to the bug.  Just providing for context)
3) Use the jar command to start the listener. 
java -jar {path-to-jar}file-leak-detector-1.16-jar-with-dependencies.jar PID http=19999

### Expected Results

Command should execute successfully 

### Actual Results

The command does not complete and returns with the following error 

`com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:170)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.kohsuke.file_leak_detector.Main.run(Main.java:74)
        at org.kohsuke.file_leak_detector.Main.main(Main.java:38)
`

### Anything else?

We can only use Amazon Corretto, it seems many other JVM's work including Bell & SAP

**Comment by Rodrigolmti** [comment]
The same problem happens with JetBrains Runtime 17.X.X, on an Android project.

**Comment by timja** [comment]
Closing as no response to the question about using the latest version
