### ISSUE TITLE
Doesn't work on IBM Java: ATTACH_ERR AgentInitializationException102

### ISSUE THREAD

**Issue by candrews** [jenkinsci/lib-file-leak-detector#18]
I'm trying to attach to a running process; this works great on the Sun/Oracle/Open JDK, but I can't get it to work on the IBM JDK.

<pre>
root@ibmserver:/apps/IBM/WebSphere/AppServer/java/bin>java -jar /root/file-leak-detector-1.7-jar-with-dependencies.jar 5177488 http=19999
Connecting to 5177488
Activating file leak detector at /home/achinich/file-leak-detector-1.7-jar-with-dependencies.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
        at java.lang.reflect.Method.invoke(Method.java:611)
        at org.kohsuke.file_leak_detector.Main.run(Main.java:56)
        at org.kohsuke.file_leak_detector.Main.main(Main.java:35)
Caused by: com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
        at ibm.tools.attach.J9VirtualMachine.loadAgent(J9VirtualMachine.java:66)
        ... 6 more
</pre>

**Comment by christ66** [comment]
I believe in order for you to attach to the JVM you would need to run the command as the _same_ user that's running the java process. You are running the command as `root`, but the process is ran by user `tomcat7`, so this would error. You can get this error also if you perform a `jstack` command as a different user from the one running the jvm. The only way around it would be to run `jstack -F` which will force attaching to the jvm process.

**Comment by zrlw** [comment]
file-leak-detector for WebSphere Application Server 8.5 (IBM JDK 1.6)
https://github.com/zrlw/file-leak-detector
